#!/usr/bin/env php
<?php

use Symfony\Component\Console\Input\ArgvInput;

define('LARAVEL_START', microtime(true));

// Register the Composer autoloader...
require __DIR__.'/vendor/autoload.php';

// Bootstrap Laravel and handle the request...
/** @var \Illuminate\Contracts\Console\Kernel $kernel */
$kernel = (require __DIR__.'/bootstrap/app.php')->make(Illuminate\Contracts\Console\Kernel::class);

// Exit code 0 for success, 1 for failure
$status = $kernel->handle(
    $input = new ArgvInput,
);

$kernel->terminate($input, $status);

exit($status);
